MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 16384
  head_bottleneck_dim: 128
  head_nlayers: 3
  head_hidden_dim: 512
  koleo_loss_weight: 0.1
  crop_local: False
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  noise_replace_p: 0.1
  separate_head: false
  head_n_prototypes: 16384
  head_bottleneck_dim: 128
  head_nlayers: 3
  head_hidden_dim: 512
train:
  batch_size_per_gpu: 9
  dataset_path: ImageNet:split=TRAIN
  output_dir: .
  saveckp_freq: 20
  seed: 0
  num_workers: 10
  OFFICIAL_EPOCH_LENGTH: 2324
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
student:
  arch: vit_large
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 4
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 7
optim:
  epochs: 30
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.003  # 0.004 learning rate for a batch size of 1024, neuro_num 93,415
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 2
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  local_crops_number: 4
  global_crops_size: 
  - 200
  - 500
  - 1000
  local_crops_size: 
  - 40
  - 100
  - 200
evaluation:
  eval_period_iterations: 2324
dataset:
  path: "/mnt/data/aim/liyaxuan/pre_data/"
  jitter_var: 1
  translate_var: 10
  rotation_axis: "y"
  n_drop_branch: 10
model:
  dim: 128
  depth: 7
  n_head: 11
  feat_dim: 11
  pos_dim: 128
  num_classes: 1000